stages:
  - build

cache:
  paths:
    - app/node_modules/
    - bower_components/
    - node_modules/

build:mac:
  stage: build
  tags:
    - mac
  before_script:
    - npm install
    - ./node_modules/.bin/bower install
  script:
    - npm run release

build:windows:
  stage: build
  tags:
    - windows
  script:
    - npm install
    - cd app
    - npm install
    - cd ..
    - npm run bower
    - npm run release'
