import { PROJECTS } from './projects';

export interface DATAPOINT_STATE {
  name: string;
  isChecked?: boolean;
}

export const EXPECTED_DATAPOINTS_BY_PROJECT: Record<PROJECTS, DATAPOINT_STATE[]> = {
  [PROJECTS.OFFICE_HVAC]: [
    {
      name: 'Baseline',
      isChecked: false
    },
    {
      name: 'Fan Coil DOAS',
      isChecked: false
    },
    {
      name: 'VAV DX',
      isChecked: false
    },
    {
      name: 'Radiant DOAS',
      isChecked: false
    },
    {
      name: 'VAV Chilled Water',
      isChecked: false
    }
  ],
  [PROJECTS.OFFICE_STUDY]: [...Array(80).keys()].map(num => ({
    name: `DOE Autogenerated ${num + 1}`
  })),
  [PROJECTS.NEW]: []
};
