name: Playwright Tests
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install build dependencies
        run: npm i
      - name: Build application
        run: npm run build -- --env=test
      - name: Install runtime dependencies
        run: npx gulp installDeps
      - name: Prepare tmp test files
        run: npx gulp tmpTestFiles
      - name: Run Playwright tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            "/home/runner/work/OpenStudio-PAT/OpenStudio-PAT/depend/ruby/bin/ruby" "/home/runner/work/OpenStudio-PAT/OpenStudio-PAT/depend/OpenStudio-server/bin/openstudio_meta" start_local --worker-number=1 --energyplus-exe-path="" --openstudio-exe-path="/home/runner/work/OpenStudio-PAT/OpenStudio-PAT/depend/OpenStudio/bin/openstudio" --ruby-lib-path="/home/runner/work/OpenStudio-PAT/OpenStudio-PAT/depend/OpenStudio/Ruby" --mongo-dir="/home/runner/work/OpenStudio-PAT/OpenStudio-PAT/depend/mongo/bin" --debug "/home/runner/work/OpenStudio-PAT/OpenStudio-PAT/.tmp-test/Office_HVAC"
            npx playwright test -c playwright-serial.config.ts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: reports/playwright/
          retention-days: 30
