name: Playwright Tests
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install build dependencies
        run: npm i
      - name: Build application
        run: npm run build -- --env=test
      - name: Install runtime dependencies
        run: npx gulp installDeps
      - name: Prepare tmp test files
        run: npx gulp tmpTestFiles
      - name: Run Playwright tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            npx playwright test
            npx playwright test -c playwright-serial.config.ts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
